apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: voting-app
  labels:
    app: vote
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: voting-app-vote:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: vote-config
              key: redis.host
        - name: RESULT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: vote-config
              key: result.service.url
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
