apiVersion: v1
kind: Service
metadata:
  name: vote-metrics
  namespace: voting-app
  labels:
    app: vote
    monitored: "true"
spec:
  selector:
    app: vote
  ports:
  - name: metrics
    port: 9153
    targetPort: 9153
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: voting-app
data:
  scrape-interval: "30s"
  metrics-path: "/metrics"
  timeout: "10s"
  enabled: "true"
