apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: voting-app
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vote-pod-reader
  namespace: voting-app
subjects:
- kind: ServiceAccount
  name: vote-service-account
  namespace: voting-app
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: voting-app
  name: configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vote-config-reader
  namespace: voting-app
subjects:
- kind: ServiceAccount
  name: vote-service-account
  namespace: voting-app
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
