apiVersion: v1
kind: ResourceQuota
metadata:
  name: voting-app-quota
  namespace: voting-app
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
    services: "10"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: voting-app-limits
  namespace: voting-app
spec:
  limits:
  - default:
      cpu: 100m
      memory: 128Mi
    defaultRequest:
      cpu: 50m
      memory: 64Mi
    type: Container
